-- Tracks persona-to-persona handoffs in Chat Mode sessions.
-- UUIDs are generated by JPA before INSERT — no DEFAULT gen_random_uuid().

CREATE TABLE persona_handoff (
    id                  UUID         PRIMARY KEY,
    from_persona_id     VARCHAR(100) NOT NULL,
    from_session_key    VARCHAR(255) NOT NULL,
    to_persona_id       VARCHAR(100) NOT NULL,
    to_session_key      VARCHAR(255),
    trigger_type        VARCHAR(50)  NOT NULL,
    trigger_reason      TEXT         NOT NULL,
    handoff_summary     TEXT         NOT NULL,
    shared_context      TEXT,
    status              VARCHAR(20)  NOT NULL,
    user_id             VARCHAR(100) NOT NULL,
    created_at          TIMESTAMP    NOT NULL,
    accepted_at         TIMESTAMP,
    completed_at        TIMESTAMP
);

CREATE INDEX idx_handoff_user   ON persona_handoff(user_id);
CREATE INDEX idx_handoff_from   ON persona_handoff(from_persona_id, user_id);
CREATE INDEX idx_handoff_to     ON persona_handoff(to_persona_id, user_id);
CREATE INDEX idx_handoff_status ON persona_handoff(status);
