-- Chat Mode code generation artifacts and run tracking.
-- UUIDs generated by JPA — no DEFAULT gen_random_uuid().
-- TEXT used for content columns (H2 + PostgreSQL compatible).

CREATE TABLE chat_generation_run (
    id              UUID         PRIMARY KEY,
    session_key     VARCHAR(255) NOT NULL,
    user_id         VARCHAR(100) NOT NULL,
    persona_id      VARCHAR(100) NOT NULL,
    user_prompt     TEXT         NOT NULL,
    status          VARCHAR(20)  NOT NULL,
    artifact_count  INT          NOT NULL DEFAULT 0,
    created_at      TIMESTAMP    NOT NULL
);

CREATE INDEX idx_gen_run_user    ON chat_generation_run(user_id, persona_id);
CREATE INDEX idx_gen_run_session ON chat_generation_run(session_key);

CREATE TABLE chat_artifact (
    id              UUID         PRIMARY KEY,
    run_id          UUID         NOT NULL REFERENCES chat_generation_run(id) ON DELETE CASCADE,
    session_key     VARCHAR(255) NOT NULL,
    user_id         VARCHAR(100) NOT NULL,
    persona_id      VARCHAR(100) NOT NULL,
    file_name       VARCHAR(255) NOT NULL,
    file_path       VARCHAR(500) NOT NULL,
    language        VARCHAR(50),
    artifact_type   VARCHAR(50)  NOT NULL,
    content         TEXT         NOT NULL,
    description     TEXT,
    is_latest       BOOLEAN      NOT NULL DEFAULT TRUE,
    prompt_summary  TEXT,
    created_at      TIMESTAMP    NOT NULL
);

CREATE INDEX idx_artifact_session ON chat_artifact(session_key, is_latest);
CREATE INDEX idx_artifact_user    ON chat_artifact(user_id, persona_id, is_latest);
CREATE INDEX idx_artifact_path    ON chat_artifact(session_key, file_path, is_latest);
