package com.atlasia.ai.model;

import jakarta.persistence.*;

import java.time.Instant;
import java.util.UUID;

/**
 * A single file generated by a Chat Mode persona.
 * Supports versioning: when a persona regenerates a file at the same path,
 * the old record is marked isLatest=false and a new one is inserted.
 */
@Entity
@Table(name = "chat_artifact")
public class ChatArtifactEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", nullable = false, updatable = false)
    private UUID id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "run_id", nullable = false)
    private ChatGenerationRunEntity run;

    @Column(name = "session_key", nullable = false)
    private String sessionKey;

    @Column(name = "user_id", nullable = false, length = 100)
    private String userId;

    @Column(name = "persona_id", nullable = false, length = 100)
    private String personaId;

    @Column(name = "file_name", nullable = false)
    private String fileName;

    @Column(name = "file_path", nullable = false, length = 500)
    private String filePath;

    @Column(name = "language", length = 50)
    private String language;

    /** SOURCE_CODE | SPEC | CONFIG | TEST | MIGRATION | OTHER */
    @Column(name = "artifact_type", nullable = false, length = 50)
    private String artifactType;

    @Column(name = "content", nullable = false, columnDefinition = "TEXT")
    private String content;

    @Column(name = "description", columnDefinition = "TEXT")
    private String description;

    @Column(name = "is_latest", nullable = false)
    private boolean isLatest = true;

    @Column(name = "prompt_summary", columnDefinition = "TEXT")
    private String promptSummary;

    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    protected ChatArtifactEntity() {}

    public ChatArtifactEntity(ChatGenerationRunEntity run, String sessionKey, String userId,
                               String personaId, String fileName, String filePath,
                               String language, String artifactType, String content,
                               String description, String promptSummary) {
        this.run = run;
        this.sessionKey = sessionKey;
        this.userId = userId;
        this.personaId = personaId;
        this.fileName = fileName;
        this.filePath = filePath;
        this.language = language;
        this.artifactType = artifactType;
        this.content = content;
        this.description = description;
        this.promptSummary = promptSummary;
        this.isLatest = true;
    }

    @PrePersist
    public void onCreate() {
        createdAt = Instant.now();
    }

    public UUID getId() { return id; }
    public ChatGenerationRunEntity getRun() { return run; }
    public String getSessionKey() { return sessionKey; }
    public String getUserId() { return userId; }
    public String getPersonaId() { return personaId; }
    public String getFileName() { return fileName; }
    public String getFilePath() { return filePath; }
    public String getLanguage() { return language; }
    public String getArtifactType() { return artifactType; }
    public String getContent() { return content; }
    public String getDescription() { return description; }
    public boolean isLatest() { return isLatest; }
    public void setLatest(boolean latest) { isLatest = latest; }
    public String getPromptSummary() { return promptSummary; }
    public Instant getCreatedAt() { return createdAt; }
}
